### Today we are going to perform the simple classification of the amazon reviews' sentiment.

### Please, download the dataset amazon_baby.csv.

Here we are importing libraries to work with data, and also i have changed a little bit remove_punctation:
  - it checks if text is string
  - if it is it creates a dictionary translator which deletes all the interpunction.
  - if its not it just returns ""

  We prepare data here to analise it later.

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import string
from sklearn.linear_model import LogisticRegression

def remove_punctuation(text):
    import string
    if isinstance(text, str):
      translator = str.maketrans('', '', string.punctuation)
      return text.translate(translator)
    else:
        return ""

baby_df = pd.read_csv('amazon_baby.csv')
baby_df.head()

,name,review,rating
0,Planetwise Flannel Wipes,"These flannel wipes are OK, but in my opinion ...",3
1,Planetwise Wipe Pouch,it came early and was not disappointed. i love...,5
2,Annas Dream Full Quilt with 2 Shams,Very soft and comfortable and warmer than it l...,5
3,Stop Pacifier Sucking without tears with Thumb...,This is a product well worth the purchase. I ...,5
4,Stop Pacifier Sucking without tears with Thumb...,All of my kids have cried non-stop when I trie...,5

As we can see the dataset contains customer reviews of baby products on Amazon. It has three columns:
 - name (name of the product)
 - review (text of a customer review)
 - rating - numerical rating given by customer in range (1 - 5)

## Exercise 1 (data preparation)
a) Remove punctuation from reviews using the given function.   
b) Replace all missing (nan) revies with empty "" string.  
c) Drop all the entries with rating = 3, as they have neutral sentiment.   
d) Set all positive ($\geq$4) ratings to 1 and negative($\leq$2) to -1.

In excercise 1 we are supposed to prepare data even more, by creating a new column "review_clean" which has no punctuation.

In [26]:
#a)
baby_df['review_clean'] = baby_df['review'].apply(remove_punctuation)

baby_df.head()

print(baby_df['rating'].value_counts())
#short test:
#baby_df["review"][4] == 'All of my kids have cried nonstop when I tried to ween them off their pacifier until I found Thumbuddy To Loves Binky Fairy Puppet  It is an easy way to work with your kids to allow them to understand where their pacifier is going and help them part from itThis is a must buy book and a great gift for expecting parents  You will save them soo many headachesThanks for this book  You all rock'
#remove_punctuation(baby_df["review"][4]) == 'All of my kids have cried nonstop when I tried to ween them off their pacifier until I found Thumbuddy To Loves Binky Fairy Puppet  It is an easy way to work with your kids to allow them to understand where their pacifier is going and help them part from itThis is a must buy book and a great gift for expecting parents  You will save them soo many headachesThanks for this book  You all rock'

rating
5    107054
4     33205
3     16779
1     15183
2     11310
Name: count, dtype: int64

I have displayed the values because i needed it in analysis in c) :)


-----------
In b) excercise i have handled the missing values in the review column.

I checked if the review has any NaN`s. Then replaced any missing values with "".

This ensures that rows have a string in review, which is important for processing.

In [27]:
#b)
baby_df['review'] = baby_df['review'].fillna("")
#short test:
baby_df["review"][38] == baby_df["review"][38]
baby_df.head()

,name,review,rating,review_clean
0,Planetwise Flannel Wipes,"These flannel wipes are OK, but in my opinion ...",3,These flannel wipes are OK but in my opinion n...
1,Planetwise Wipe Pouch,it came early and was not disappointed. i love...,5,it came early and was not disappointed i love ...
2,Annas Dream Full Quilt with 2 Shams,Very soft and comfortable and warmer than it l...,5,Very soft and comfortable and warmer than it l...
3,Stop Pacifier Sucking without tears with Thumb...,This is a product well worth the purchase. I ...,5,This is a product well worth the purchase I h...
4,Stop Pacifier Sucking without tears with Thumb...,All of my kids have cried non-stop when I trie...,5,All of my kids have cried nonstop when I tried...

Basically here we have deleted the reviews with rating 3 which are the least important. Why? Because they are most neutral. Often in such an analysis these are removed to have some kind of binary classification like in excercise d) we do.

In [28]:
#c)
#short test:
print("Before dropping: ", sum(baby_df["rating"] == 3))

baby_df = baby_df[baby_df['rating'] != 3]

print("After dropping: ", sum(baby_df["rating"] == 3))


baby_df.head()

Before dropping:  16779
After dropping:  0

,name,review,rating,review_clean
1,Planetwise Wipe Pouch,it came early and was not disappointed. i love...,5,it came early and was not disappointed i love ...
2,Annas Dream Full Quilt with 2 Shams,Very soft and comfortable and warmer than it l...,5,Very soft and comfortable and warmer than it l...
3,Stop Pacifier Sucking without tears with Thumb...,This is a product well worth the purchase. I ...,5,This is a product well worth the purchase I h...
4,Stop Pacifier Sucking without tears with Thumb...,All of my kids have cried non-stop when I trie...,5,All of my kids have cried nonstop when I tried...
5,Stop Pacifier Sucking without tears with Thumb...,"When the Binky Fairy came to our house, we did...",5,When the Binky Fairy came to our house we didn...

As we said before we changed the positive ratings such as (4, 5) to 1 and negative like a (1, 2) to -1. This is standard for preprocessing for binary classification tasks.

In [29]:
#d)
baby_df['rating'] = np.where(baby_df['rating'] >= 4, 1, -1)


print(baby_df['rating'].value_counts())

baby_df.head()

rating
 1    140259
-1     26493
Name: count, dtype: int64

,name,review,rating,review_clean
1,Planetwise Wipe Pouch,it came early and was not disappointed. i love...,1,it came early and was not disappointed i love ...
2,Annas Dream Full Quilt with 2 Shams,Very soft and comfortable and warmer than it l...,1,Very soft and comfortable and warmer than it l...
3,Stop Pacifier Sucking without tears with Thumb...,This is a product well worth the purchase. I ...,1,This is a product well worth the purchase I h...
4,Stop Pacifier Sucking without tears with Thumb...,All of my kids have cried non-stop when I trie...,1,All of my kids have cried nonstop when I tried...
5,Stop Pacifier Sucking without tears with Thumb...,"When the Binky Fairy came to our house, we did...",1,When the Binky Fairy came to our house we didn...

## CountVectorizer
In order to analyze strings, we need to assign them numerical values. We will use one of the simplest string representation, which transforms strings into the $n$ dimensional vectors. The number of dimensions will be the size of our dictionary, and then the values of the vector will represent the number of appereances of the given word in the sentence.

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
reviews_train_example = ["We like apples",
                   "We hate oranges",
                   "I adore bananas",
                   "We like like apples and oranges",
                   "They dislike bananas"]

X_train_example = vectorizer.fit_transform(reviews_train_example)

print(vectorizer.get_feature_names_out())
print(X_train_example.todense())

['adore' 'and' 'apples' 'bananas' 'dislike' 'hate' 'like' 'oranges' 'they'
 'we']
[[0 0 1 0 0 0 1 0 0 1]
 [0 0 0 0 0 1 0 1 0 1]
 [1 0 0 1 0 0 0 0 0 0]
 [0 1 1 0 0 0 2 1 0 1]
 [0 0 0 1 1 0 0 0 1 0]]

What is important to notice here is that countVectorizes converts text in something like a bag-of-words representation.

We create the vectorizer, and some example of training data.

fit_transofrm does two things:
  - fit -lears the vocab
  - transform - converts each text into sparse matrix of word counts.

result X_train_example is a 5 x n matrix.

We can see that the output is in alfabethical order and the 1 and 0 are representing the words that came up in the text.

In [33]:
reviews_test_example = ["They like bananas",
                   "We hate oranges bananas and apples",
                   "We love bananas"] #New word!

X_test_example = vectorizer.transform(reviews_test_example)

print(vectorizer.get_feature_names_out())
print(X_test_example.todense())

['adore' 'and' 'apples' 'bananas' 'dislike' 'hate' 'like' 'oranges' 'they'
 'we']
[[0 0 0 1 0 0 1 0 1 0]
 [0 1 1 1 0 1 0 1 0 1]
 [0 0 0 1 0 0 0 0 0 1]]

We should acknowledge few facts. Firstly, CountVectorizer does not take order into account. Secondly, it ignores one-letter words (this can be changed during initialization). Finally, for test values, CountVectorizer ignores words which are not in it's dictionary.

## Exercise 2
a) Split dataset into training and test sets.     
b) Transform reviews into vectors using CountVectorizer.

In [37]:
#a)
from sklearn.model_selection import train_test_split
X = baby_df['review_clean']   # teksty
y = baby_df['rating']         # etykiety (-1, 1)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Train size:", len(X_train))
print("Test size:", len(X_test))

#it divides the date 80%/20%

Train size: 133401
Test size: 33351

Now we move on to the original dataset. First we are splitting data into 80% / 20%.

We can see the training and test count in the console.

In [38]:
#b)
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

# Uczymy vectorizera na zbiorze treningowym
X_train_vectorized = vectorizer.fit_transform(X_train)

# Wektor transformacji testu — NIE używamy .fit!
X_test_vectorized = vectorizer.transform(X_test)

print("Vocabulary size:", len(vectorizer.get_feature_names_out()))
print("Train matrix shape:", X_train_vectorized.shape)
print("Test matrix shape:", X_test_vectorized.shape)

Vocabulary size: 121805
Train matrix shape: (133401, 121805)
Test matrix shape: (33351, 121805)

Here again:
  - fit (learns the vocab from training set)
  - transform (COnverts the training texts into sparse matrix)

Why only use transform on test set?
We want to use the same vocab learned from training to ensure new features. New words are ignored.

## Exercise 3
a) Train LogisticRegression model on training data (reviews processed with CountVectorizer, ratings as they were).   
b) Print 10 most positive and 10 most negative words.

In [39]:
#a)
model = LogisticRegression()

model.fit(X_train_vectorized, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

X_train... - the bag of words

y_train - labels (1 , -1)

In [41]:
#b)
words = vectorizer.get_feature_names_out()
coeffs = model.coef_[0]

sorted_indices = np.argsort(coeffs)

print("Most negative words: ")
print(words[sorted_indices[:10]])

print("\nMost positive words: ")
print(words[sorted_indices[-10:]])
#hint: model.coef_, vectorizer.get_feature_names()

Most negative words:
['worst' 'disappointing' 'useless' 'poorly' 'poor' 'terrible' 'concept'
 'returning' 'returned' 'horrible']

Most positive words:
['exactly' 'highly' 'complaint' 'satisfied' 'glad' 'amazing' 'worry'
 'pleased' 'awesome' 'excellent']

As we can see in the print the negative words have strong negative coefficients, meaning their present in a review strongly predicts a negative statement.

Same case is with positive their presence increases a chance that the review was positive.

## Exercise 4
a) Predict the sentiment of test data reviews.   
b) Predict the sentiment of test data reviews in terms of probability.   
c) Find five most positive and most negative reviews.   
d) Calculate the accuracy of predictions.

In [43]:
#a)

y_pred = model.predict(X_test_vectorized)

print(y_pred[:10])

[ 1 -1 -1  1  1  1  1  1  1 -1]

1 means that the model predicts the review is positive

-1 means that was negative

This is simply a models classification output for reviews in test set.

In [44]:
#b)
y_proba = model.predict_proba(X_test_vectorized)

print(y_proba[:5])
#hint: model.predict_proba()

[[0.39808426 0.60191574]
 [0.79754664 0.20245336]
 [0.70249309 0.29750691]
 [0.00154467 0.99845533]
 [0.00401972 0.99598028]]

predict_proba() returns the model`s confidence for each review for each review: probability it is negative vs positive

usefull for ranking reviews by sentiment strength

In [47]:
#c)

sorted_indices = np.argsort(y_proba[:, 1])

most_negative_idx = sorted_indices[:5]

most_positive_idx = sorted_indices[-5:]

print("Most positive reviews: ")
for i in most_positive_idx[::-1]:
  print(f"Prob={y_proba[i, 1]:.2f} | Review: {X_test.iloc[i]}\n")

for i in most_negative_idx[::-1]:
  print(f"Prob={y_proba[i, 1]:.2f} | Review: {X_test.iloc[i]}\n")


#hint: use the results of b)

Most positive reviews:
Prob=1.00 | Review: My husband and I cannot state enough how much we value and appreciate this swing No amount of money could have provided to us and our baby what this swing has offeredThis swing has brought peace quiet and happiness to our household Our newborn baby girl was a bit colicky when she was first born for the first 8 weeks She would sleep well through the night but would be fussy and not willing to sleepnap during the day She wanted to be rocked to sleep which left our arms very tired and sore Well this swing to the rescue It puts our little girl to sleep in less than 10 minutes but not before it thoroughly entertains her with its mirrored surface that the baby faces She loves it and coos at it all the time its wonderful mobile that she loves and even the sounds which she very much appreciates I also love how the direction of swinging can be changes from front to back or side to side Our daughter did not care for the side to side motion but LOVED back to front motion settingAdditionally the harness is comfortable safe and easy to use with the baby The Snuggabunny design is beyond adorable and very comfortable for the baby It is relatively easy to assemble and set up The only negative is that it would be difficult to store and takes up a good amount of room Howver the benefits highly outweigh this one short comingI feel that our daugher not only gets to relax and nap better with the swing the swing is also good for her development as she learns about her reflection follows the mobile around and gets stimulated by a variety of sounds The multitude of speed settings is also very convenient as she usually starts swinging at full force but later we can adjust her to the lowest setting for a more calm sleepingWe decided to purchase a swing on the recommendation of Dr Harvey Karp author of Happiest Baby on the Blocka highly recommended book and it has been wonderful Well worth the money I am finding myself to be more and more impressed with Fisher Price as of late as all of the purchased baby products produced by them by us have been greatOur daugher is no longer colicky past 8 weeks of her life thank you higher power but she still enjoys her swing and loves swinging as we enjoy some peace quiet and watching her being so happy and entertainedOur highest recommendations

Prob=1.00 | Review: For starters its the only stroller my little girl will fall asleep in which in itself is wonderful when we are gone all day  Other strollers she would stay up all day long and you can imagine what that was like for a little one and for us  Its padding is obviously comfortable to her  You can just feel the quality in itI think the best part is the canopy  Its basically lights out for her when we are out in public  With the extra sun shade that folds out it makes it nice and dark in there  Love the peek a boo window so I can keep an eye on her sitting or sleeping and you can cover that window back up with the cover if you want it fully dark inside  So many positions to the canopy also  And its got UV protectionAlso love the full recline but be advised in full recline position dont expect to get much from the cargo area underneath  It does have side zippers underneath where you can pull some stuff out  It has these awful support bars that go across the cargo area making it half useless  Definitely needs improvement there  I do store jackets under the bar deep down into the cargo bag and put my purse on top of the bars but I have a smaller purse  You will not get a full size diaper bag in there or any diaper bag for that matter so dont expect to use this as a full size stroller  Its an umbrella stroller  More for on the go in and out kind of trips though I do use it at the mall  I did decide to purchase the OXO Tot Stroller Hook  Its great for my purse and shopping bags also which I hang my purse on when the baby is going to recline back for nappyIt comes with one cupholder but coming from a stroller that had 2 it was a definite must have  I was able to secure one by ordering through Kiddy USA and contacted them via their facebook page so now we have 2  And yes there is a hook on both sides of the stroller so if you have just one cup holder you can switch the side you keep it on  It is also removable by just lifting up  It connects via a small peg that stick out from the stroller  Very simple to useThe bumper bar in the front is fully removable and it also bends completely upward if you have a younger baby in the seat and dont want to bother removing it  I thought we would be removing it but the baby actually really likes it  She likes holding on to it having her toys attached to it via links and we also purchased the Brica Snack Pod which we attach right to the bumper bar  Gives her a place for a drink and snack alsoThe height of the handlebars works just fine for me and my husband  I am 5ft 1 and he is 5ft 7  They are not adjustable  I thought it would be a little tall for me but when I compared it to our old Maclaren umbrella strollers the height was the same  From the floor to the top of the handle you are looking at 41  Your hands will obviously be lower than that  They are nicely padded for comfortThe seat width is 13  The backrest where the back meets the seat is 20  The seat has a foot extension so baby can have their legs directly out  In that position the seat length is 13 from front to where it meets the backrest at the back  When the foot extension is in the down position the seat depth is roughly 10 from the bend of the foot extension to the back of the seatIt does include a 5 point harness and while many of the newer strollers do not have a crotch strap that is long enough this one seems sufficient as the baby growsLets see what else  Oh the back of the backrest does have a pocket which is great for throwing keys or a phone or pacis etc  I do wish it had a zipper closure so I could put those things in and feel they are a little more secure when my back is turned but its not a big issue for me  It just kind of pushes to and is covered a bit with the extra part of the canopyAs for the wheels they are a nice size at 6 which is what I preferred for an umbrella stroller but dont expect them to go through heavy snow if you live in a harder winter climate like we do in the midwest  We have actually kept our full size stroller for that purpose and will use this one through the spring summer and fallThis stroller is very easy to fold  One pull of a tab at the back and one push on foot pedal at the side and fold and you will hear a click of the side latch locking mechanism done  It does weigh more than cheaper umbrella strollers but I account a lot of that to the durability of the frame  You can just see and feel the difference  Definitely not plastic like and cheap  They are solidOne thing I do wish since this stroller comes from a family owned company in Germany which I love I do wish the company would expand more into the USA  While I was able to secure another cupholder I am not able to secure a footmuff or the matching diaper bag or a rain cover  These items are overseas only  I have only found one company that will ship the footmuff to the United States but its at a hefty cost obviously so we will probably end up going with a JJ Cole footmuff insteadThere is a video of this stroller on youtube that I would highly recommend  It is not in English but watching it you will get just about all the information you need  It was actually what sold me on this stroller  Go to youtube and put this in the search bar to watch the video  oacuteiacuteagrave ntildeagrave Kiddy Cityn MoveI hope my review has helped you decide if this stroller is right for you  We purchased this stroller in Walnut because I wanted something neutral for resell purposes later and its perfect  I gave this stroller 4 of 5 stars because of the cargo area cross bars that block getting in and out of the storage area easily as well as the unavailability of accessories here in the United States

Prob=1.00 | Review: I did a TON of research before I purchased this stroller and I still watch stroller reviews all the time Babygizmocom has really great reviews on so many strollers And Zooper Waltz 2011 is THE BEST of all Ive seen so farLet me tell you first though that it is not an allterrain or jogging stroller and it does not have an ability to be used for more than one child So if youre looking for these things this is not it But if youre looking for a single stroller for city walking and a little bit of park and dirt etc and you dont want a monster stroller size and weight wise this is the best stroller of that kindOne of my favorite things about this stroller is that it comes with SO many accessories that are sold separately on most other strollers especially those expensive ones With this one you pay 300 I paid 250 for it on eBay and get the following accessories all included A UV netIt easily snaps onto the canopy to completely shade the front and there are two elastic loops at the bottom to attach it securely to the stroller It comes in a zippered pouch and whats genius about it is that the pouch itself is actually part of the net so you dont have to worry about ever losing the pouch A foot muff for cold weatherIt also easily snaps onto the seat This is something you dont see included with a stroller very often A removable cup holderIt can actually hold a travel mug Starbucks cup etc and not just a water bottle A snack tray for the childLarge enough to be actually practical Has a large deep cup holder that securely holds any sippy cup a bowllike section to put some snacks and two compartments in the middle A baby bumper barYou can either completely remove it or just swing it away to make it easier to get your child in and out of the stroller Infant car seat adapter strapsYou attach it to the Drings on the sides of the seat then it goes over your infant car seat and you secure it with a buckle and by tightening the strap Its not one of those big bulky frame adapters that some strollers have for infant car seat To me thats just one more thing to find a place for when youre not using it as a travel system This strap system feels very very secure and its just much more travel friendly A rain coverThe 2011 model does not come with a rain cover but thats because the improved canopy which is gigantic and fullcoverage is made of complete waterproof fabric and acts as a rain cover I love this because I dont have to worry about forgetting the rain cover at home or fiddling with it trying to put it on when it starts raining unexpectedly on the goSo only 300 with all these amazing practical accessories is absolutely the best price for its valueNow on to the stroller features Thats right I havent even started on the main stroller yet LightweightIts just under 19lbs Im petite and dont have a lot of arm muscle but I dont have any problem getting this in and out of my trunk or carrying it up a couple flights of stairs every once in a while High weight capacity of 55lbsNot that I would use it for a 55lbs child regularly but it means its that sturdy Easy to assembleIt comes in a big box and all you have to do is snap on the wheels and the canopy Super easy Took us 5 minutes However I do want to note that we attached the canopy wrong at first and because of that it ripped at the zipper when we tried to recline the seat There are four snaps on the bottom of the canopy one set at the very front on each side and another in the middle The front set snaps onto the sides of the seat and the middle ones onto the back of the seat Our mistake was attaching the front ones to the seat back But Zooper had a super nice warranty service where they sent us a brand new canopy for no charge even though it was our fault Newborn friendlyIt has a very flat recline position and the leg rest goes all the way up and securely zips on to the sides of the seat creating a bassinetlike environment The leg rest also lays flat for babies or goes down for older kids It also has an infant guard at the top of the seat that would prevent your infant from ever sliding out of the seat when the seat is fully reclined and the back of the canopy is removed But this piece can be tucked away with an attached velcro once your child gets taller It also comes with an infant head rest that is attached to the shoulder straps but this is also removable Onehanded open and fold and stands on its own when foldedNow theres a trick to doing it onehanded Its supposed to be done with two hands and its super easy to do but you can also do it onehanded To open it you unlock the lock on the side push the big button on the handle bar and instead of grabbing the small handle on the side like you would when youre opening it with two hands you just push down on the top bar of the basket with your foot To fold it first you retract the canopy and put the seat up to the upright position lock all the wheels and then push the big button on the handlebar lift up on the small handle on the side with your knee just a little nudge and then you push the whole stroller down towards the ground with the handlebar That allows the frame to slide into a folded position Then I usually have to push down on the front of the frame with my foot to engage the lock It might sound complicated but once you get the hang of it you can do it in seconds My babys been real clingy and so its been nice being able  to open and fold the stroller while holding him Fullcoverage canopy with a large viewing windowThis canopy is probably my favorite feature of this stroller First of all its huge and it folds all the way down to the bumper bar to completely shade and cover your child It has a large viewing window with a flap to cover it when not in use The flap has no noisy velcro on it so you wont have to worry about waking up your baby When the seat is fully reclined but you still want fullcoverage on your sleeping baby you can actually unzip whole another fullsized panel to do that Also theres another zipper on the canopy that you can unzip and reveal a mesh underneath the back of the canopy This enables a good airflow through the back into your child The whole back of the canopy and the mesh underneath it are both completely removable as well Great storageThe basket is huge and can fit my diaper bag another big bag with beach towels and blankets jackets water bottles and lunch fairly easily So its perfect for picnics and shopping It has a hard bottom so that you will never be dragging your stuff on the ground An amazing feature of this basket is that they put a vertical zipper on each side of the basket towards the front of the stroller that goes all the way to the bottom so you will have a complete access to the content even when the seat is fully reclined I love it I also like that the side fabric of the basket is kind of seethrough so you can see where everything isAlso there is a large pocket on the back of the canopy where I can fit my clutchsize purse and another pocket on top of it with a lid which is perfect for keeping your keys cellphones etc Theres another small pocket on the back of the seat where the warnings are supposed to go but thats where I keep my UV net and car seat adapters Onehanded bar recline that has 4 different positionsI can even adjust the recline up and down while walking with this stroller Seat fabric machinewashableThe seat fabric comes off to be machinewashed Canopy is spot clean only Excellent maneuverabilityIt pushes really well and as long as Im on a paved street I can totally push it and even turn it onehanded with the baby and tons of stuff in the basket It does pretty good on grass dirt and gravel but I usually need two hands to turn on rough terrain Carrying handle on the side and the ability to wheel behind when its foldedCarrying handle is definitely nice when I lift it up to put it in my trunk and if you have the front wheels locked you can wheel it behind you like a luggage Front swivel wheels that can also be locked straight for rougher terrain and onetouch rear brakeThis is pretty standard for most strollers but its definitely a nice feature All four wheels have suspension systemIve taken it on grass and some dirt roads and it pushed very well Padded five point harness that are height adjustableThis is pretty standard too and you do have to rethread the shoulder straps to adjust the height but you wont be adjusting them all the time so this is not an issue The paddings on the shoulder straps are easily removable The buckle is easy to do no puzzle pieces You can also detach the shoulder straps and use it as a 3 point harness once your child is old enoughAs you can tell I just cannot say enough good things about this stroller Ive been using it for almost 7 months since my son was a newborn and I absolutely love itZooper also has Bolero and Twist and the differences areBolero is 400 and comes with a bassinet kit to make the seat a real bassinet Its a tad bigger and heavier but has a more compact standing fold than WaltzTwist is 200 and has an umbrella fold It can not stand on its own when folded but everything else is the same as Waltz


Most positive reviews (Prob around 1.00)
  - These reviews have the highest predicted probability of being positive
  - The model is almost certain these reviews express strong satisfaction

Most negative reviews (Prob around 0.00)
  - These reviews have the lowest predicted probability of being positive

Reviews that are long still can be classified correctly as long as the overall sentiment is consistent.

In [49]:
#d)
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test_vectorized)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy on test set: ", accuracy)

Accuracy on test set:  0.9336151839525052

Out of all the reviews in my test set about 93% were correctly classified as positive or neative in this model.

Very strong performance.

## Exercise 5
In this exercise we will limit the dictionary of CountVectorizer to the set of significant words, defined below.


a) Redo exercises 2-5 using limited dictionary.   
b) Check the impact of all the words from the dictionary.   
c) Compare accuracy of predictions and the time of evaluation.

In [50]:
significant_words = ['love','great','easy','old','little','perfect','loves','well','able','car','broke','less','even','waste','disappointed','work','product','money','would','return']

In [53]:
#a)
from sklearn.feature_extraction.text import CountVectorizer

vectorizer_limited = CountVectorizer(vocabulary=significant_words)

X_train_vectorized_limited = vectorizer_limited.fit_transform(X_train)
X_test_vectorized_limited = vectorizer_limited.transform(X_test)

print("Vocabulary size:", len(vectorizer_limited.get_feature_names_out()))
print("Train matrix shape:", X_train_vectorized_limited.shape)
print("Test matrix shape:", X_test_vectorized_limited.shape)

Vocabulary size: 20
Train matrix shape: (133401, 20)
Test matrix shape: (33351, 20)

Here we restricted the vocabulary to predefined set of significant words.

This means the model will only consider these 20 words when converting text into a numerical matrix.

All other words are ignored, which simplifies the space and focuses the model on words that are meaningfull.

In [54]:
from sklearn.linear_model import LogisticRegression
import time

model_limited = LogisticRegression(max_iter=1000)

# Measure training time
start_time = time.time()
model_limited.fit(X_train_vectorized_limited, y_train)
train_time = time.time() - start_time

print(f"Training completed in {train_time:.2f} seconds")

Training completed in 0.26 seconds

Created a Logistic Regression classifier and trained it on the vectorized training data (using only the significant words).

Measured the training time.

In [55]:
coefficients = model_limited.coef_[0]

# Most positive
top_positive_idx = coefficients.argsort()[-10:][::-1]
top_positive_words = np.array(significant_words)[top_positive_idx]

# Most negative
top_negative_idx = coefficients.argsort()[:10]
top_negative_words = np.array(significant_words)[top_negative_idx]

print("Most positive words:", top_positive_words)
print("Most negative words:", top_negative_words)

Most positive words: ['loves' 'perfect' 'love' 'easy' 'great' 'little' 'well' 'able' 'car'
 'old']
Most negative words: ['disappointed' 'return' 'waste' 'broke' 'money' 'work' 'even' 'would'
 'product' 'less']

Looked at the model coefficients for each word.

Sorted words by coefficient values:

Top positive → words strongly associated with positive reviews.

Top negative → words strongly associated with negative reviews.

In [56]:
# Predictions
y_pred_limited = model_limited.predict(X_test_vectorized_limited)

# Probabilities
y_proba_limited = model_limited.predict_proba(X_test_vectorized_limited)[:,1]  # positive class

Used the trained model to predict sentiment on the test set.

Also predicted probabilities that each review is positive (predict_proba).

In [57]:
sorted_indices_limited = np.argsort(y_proba_limited)

most_negative_idx = sorted_indices_limited[:5]
most_positive_idx = sorted_indices_limited[-5:]

print("Most positive reviews (limited dictionary):")
for i in most_positive_idx[::-1]:
    print(f"Prob={y_proba_limited[i]:.2f} | Review: {X_test.iloc[i]}\n")

print("Most negative reviews (limited dictionary):")
for i in most_negative_idx:
    print(f"Prob={y_proba_limited[i]:.2f} | Review: {X_test.iloc[i]}\n")

Most positive reviews (limited dictionary):
Prob=1.00 | Review: We bought this stroller after selling our beloved BOB rev on craigslist We used the BOB for 9 months for my son but it just wasnt practical I dont jogrun it didnt have a big basket and was very bulky to take into stores quickly However I did love how it unfolded easily but it was heavy to fold up and lift into my small trunk myself Overall I didnt realize what Id need in a stroller until AFTER I had my son Live  learn We did love how easily the BOB would go over pretty much anything Nevertheless we sold it and after extensive research on strollers we decided it was between the uppababy brand because of the large baskets OR the city mini GT because of its easy fold up design After looking over both strollers I decided on the uppababy cruz because of a few main factors It SITS UP I cant tell you how much my son hates being reclined when he is just riding in the stroller and not napping The BOB and the City Mini had a slight recline and he always tried sitting more upright The uppababy sits up like your sitting in a chair He loves it It also reclines nearly flat The foot rest can be positioned upwards so that its as if he is sitting on the floor because he is so upright and his feet are out in front of him Also the LARGE basket was a HUGE plus I cant tell you how great evvvvverything fits in there Its perfect and soooo easily accessable The city mini gt did NOT have a big enough basket for me and there for was not the right choice for me despite the very easy fold up The true test for us was this past weekend when we took it to Maine on a camping trip YES it is no BOB However I thought it was just fine over the rough bumps of a campground Bumpy ride Yes But nothing my 10 month old couldnt handle and honestly It wasnt that bad We took it to old orchard beach and as I suspected it didnt roll over the sand like my good old BOB did But it rolls really nicely on pavement and I just carried my son over to the beach and I figure he will be 1 soon enough and walking so I wont need the stroller on the beach anyways I also love the reversable seat that comes in handy because my son is going through some sort of attachment to mommy thing so he likes being able to face me from time to time I also love that the Cruz is a less expencive option to the Vista The vista is much much heavier and a little bigger And since we didnt need the extras that the Vista comes with this was the better option for us Also I called Uppababy and asked about a belly bar and toddler board for the cruz and they told me that BOTH would be available The belly bar will be out this summer and the board is in producton huge plus So for us this stroller was a hit but as anything goes you MUST research what YOU need in a stroller and figure out whats important to you Some people dont care about a big basket and in that case id for sure go with the City mini gtUPDATE1713We are in LOVE with this stroller still It fits great in the trunk of my saturn ion and how I fold it is I take the seat off first takes 1 second and then fold the frame I found it fits and folds better that way plus some times my son likes to sit forward and sometimes backwards still so I just set up the frame and then throw the seat on top depending on which way i think he wants to sit The basket is just my fave feature I cant tell you how happy I have been with the uppababby My son is 16 months old and loves sitting in his uppababy well worth it still

Prob=1.00 | Review: We love this highchair  We have a 4 year old and an 8 month old  This is our 3rd highchairFeatures we loveFit  This chair FITS my infant daughter  She fits in this chair without the extra insert way better than in the basic Evenflo chair we had before  I only use the 3point harness and let her shoulders be free and she sits at a correct level so her arms can move around well and she can lean and reach for things on the tray  Many other chairs have a real problem with fit  So I do believe that with the insert this is the perfect chair to start your 4 month infant in for feeding  The insert will make them more secure kind of like their carseatTray Insert  With our other chairs the tray clicks down into the larger tray all the way aroundyou can remove it for cleaning  Fine  But I always hated that food got into the crack nearest to the baby so I couldnt just wipe it downI HAD to remove it to get out all the gunk  The tray on this is so smartthe edge closest to the baby wraps all the way down and clicks under the lip of the large trayone smooth surface where all the food is landing  I love itUpholstry  I love this leather look  It cleans easy and is really cushy  The part that is designed to match other Graco gear is just an insert for small infants  The rest of it is just a tan color and it matches anythingSturdiness  I cant tell you how much safer I feel my daughter is in thisit is solid  I never felt terribly comfortable reclining her in other seats but this one is made well and I am not worriedVersitality  This is one of the best parts  We bought this and now we are using both the highchair for our 8 month old daughter and the booster for our 4 year old son  Here is how it works  Basically it is like a high chair with 2 bases  Both bases are toddler chairs themselves  I will call them the rolling base and the chair base  So you have a toddler seat attached to the rolling base and another toddler seat that you can attach with straps to a chair the chair base  Then you can take the separate highchair part and click it into the rolling base or to the chair base whichever you like  Then the unused base becomes a toddler chair  One might think that you could sit 3 children2 toddlers in the bases and then an infant in the highchair part but the highchair really needs to click into a base because it is not designed to be on its own  The highchair with the chair base would be great to take when traveling especially if you just use the snack tray and leave the large tray at home  And the toddler seat that is attached to the highchair frame is truly good for getting under tables with a lip because of its low sides unlike many toddler seats that come up too far and you cant scoot them under the tableWorth notingI see no problem with the snack tray  At 8 months my daughter fits fine and it is half as big as the traya great size snack tray  And it has its own separate cup holder  You really dont need the snack tray before they start feeding themselves so I cant see it being a problem at the age you would need itAdjustable foot rest  I just love this and it just makes it better for the baby to have more support  My 8 month old cant touch the highest setting yet but probably within 6 months or soToddler seat  I thought it was extra great that they include an adjustable backthere are 3 slots to put slide a back into the chairthat way you can match the length of the chair to your childs legs  My 4 year old is big enough that we removed the back and let him sit all the way back in order that is knees bend in the right place  But I can see where this would be a great feature for perfect fit through the yearsThis really is a great chair for every possible use infant toddler preschooler traveling having an extra seat if you have other kids over to your house  The system will seat 2 children at once 1 baby with tray and 1 older child OR 2 older childrenWe love thisworth every penny

Prob=1.00 | Review: Weve been using Britax for our boy now 14 months old since his very first moments leaving the hospital  Thankfully cost was not part of our consideration so we went with the best seat we could find  Britax has been good but I wish we had found the Pria  Its a terrific car seatThree best parts so far1  Head control2  Style3  Cup holder4  Soft easy to clean fabricHead control  My biggest concern with other car seats has been his head  When our son sleeps in the car he tilts his head to the side much like my father does now  But with my Dad I dont worry too much because he always seems to wake up after a few minutes and straighten out  But babies dont seem to do that well and Ive been concerned that hes closing off airway or blood to his head  Im not a doctor but it doesnt look good to me  Weve tried rolling his little blanket and stuffing it by his neck like an airplane pillowto no avail  He just tosses it on the seat  This seat has a great system for controlling his headStyle  This seat is attractive  We never used the infant insert but it has an elegant shape to it  The rest of the seat looks good too  I know its not a big concern but I do appreciate great designCup holder  It has a perfectly placed cup holder  We use the Uppababy stroller and it has a great tray where our son has become used to storing his cell phone and other things  Without a cup holder close to his hands in our car everything sits between his knees which makes it all tough to reach  Prias solution is perfect and I dont find myself reaching into the back seat as muchGreat fabric  We love the soft feel of this seat  Its almost like a good pillow  And the fabric has proven quite easy to cleanOverall were thrilled with the seatHope you enjoy yours tooPhilUPDATE Its been over a year now and we remain thrilled with this seat We kept the Britax so wed have an extra seat in the car for James friends to ride together with us Night and day this seat remains the hands down winner for easy buckling in easy cleaning and comfort And the cup holder continues to be the perfect place for drinks snacks or a little toy carWasnt sure this seat would make it this long as the fabric doesnt feel as tough as the Britax But it sure has Whatever they used is as easy to work with now as the day this one arrived And remains easy to clean Were having another one soon so the Britax will be moving to the middle seat to make room for another MaxiCosiAny recommendations on a new color

Prob=1.00 | Review: I did tons of research on strollers I knew I wanted a stroller that was light all terrain that could handle jogging and easy maneuverability My husband thought I was nuts for putting so much time into our small investment It came down to a mountain buggy urban and bumbleride indie I am beyond elated I chose the Bumbleride for our 5 month old DD1 easy to out together2 very light3 movespushes like buttah So easy especially when jogging I dont jog in a straight line yet My path has lots of turns so I dont lock the front wheel and it does great I easly jog with 1 arm freeswinging the other has the jogging strap around my wrist and pushing4 big basket I can put much more in it than my Chicco stroller5 canopy  it does exactly what its meant for Its huge and does its job well I live in Louisiana and its quite sunny here The canopy can shade my DD all the way to her toes It almost is like a cocoon  She loves it6 folds well overall Id give it a 7 I dont think youre going to find another stroller with a more compact fold with all the other great features the indie has I own a suburban so its not a room issue for me Its a little tricky at first but easy once you get it7 recline I like that it doesnt have stations Just squeeze the thingie and let as much in or out Easy to useI do wish it had a trayrack for the pusher to put stuff Mine did come with a cup holder you can attach 2 1 on either side The canopy has a zipper pouch that can old keys and a cell phone and more little thingsOverall I love this stroller Its a great smooth ride My DD falls asleep during our walks all the time I know it will grow with her I ordered mine and did not get the opportunity to test drive any I Know I made the right choiceUpdate 5232012My mother just bought a Phil  Teds Classic to keep at her house for when we visit There is no comparison Bumbleride is a much better push and easier to collapsefold Seriously I was shocked at how different the pushes where Our Bumbleride is sooo smooth I can whip it around when going through push doors Ive been doing some walkingrunning intervals and it handles so well After all the research I did I could not be happier with our Bumbleride

Prob=1.00 | Review: UPDATE 112013  I went ahead and used a tiny bit of WD40 and also thoroughly cleaned the carseat base and stroller and all the mechanisms started working like new again  No more issues opening or closing the stroller and no more issues getting the seat out of the baseMy child was finally moved out of this seat at 14 months and placed in a transitional carseat rear facing of course and I sold the entire system on craigs list for 150 including two bases  For something I got so much use out of to be able to resell it for that amount of money is unheard of  I even had people offering me more after I had already sold it  So I am now convinced this was a very smart purchase and I sure got a lot of use out this travel system  I am not going to lie I was almost tearful seeing it go to a new home I had become that attached UPDATE 72313  Okay I have been using the heck out of this travel system for 11 months now  I am not as enamored with the system as I was when I first bought it and here is why1 The fabric gets very very very dirty and grungy looking and it hard to take apart and clean2 The stroller no longer easily opens with one handI have to play with it  I am afraid it is due to all the use we use this thing a lot and it has been on a lot of plane rides but the mechanism is frustrating now  I am going to try some WD40 soon to see if that will help3 My kid is 11 months old and still uses it so that is a BONUS  Yeah a break from buying more car seats for a while  He is  big kid too4 The mechanism for getting the car seat out of the base is kind of tricky now too  Most of the times it is fine but some days I dont think I will ever get it to unlatchI still like it but for the price tag I would get a Britax stroller and infant car seat combo in the future if I ever have more childrenI am a 3rd time mom but it has been 5 years since my last baby  I wanted a car seat with a stroller that would be easy to use by myself and would be easy to install in the car  I also wanted a one with a good safety rating  So after reading multiple reviews and consumer reports on many different travel systems I found this one and went ahead and took the plunge site unseen they dont carry Chicco at our local walmart and I live hours away from a store that does  My baby is now 5 weeks old and I have been using the heck out of the system so here is what I think so farCar seat prosThe car seat is EASY take in and out of the base  I had a Graco Snuggleride with my last one and I thought that was easy but the Chicco blows it away  It was also super easy to install in my car and in my SUV  The clips to attach to the LATCH system and really easy to use and the level makes it easy to know you have a the proper angle for the seat  It was much more difficult with the Graco seat that is for sure  The straps are easy to use and adjust and the car seat looks very nice and stylish  I got the Miro patterned fabric and it is lovely and gender neutral which was a big deal to me because this was a surprise baby  It just looks and feels to be of high qualityCar seat consThis seat is heavy I carry it a lot but I always opt to use the stroller with the car seat it I am going to be walking any short distance because the seat with my baby just seems like a lot to lug around  I know my Graco one wasnt this heavy  Also it doesnt fit into a shopping cart very easily making shopping with baby without the assistance of another person pretty difficult  I finally started just carrying my infant son with my baby Ktan and leaving the car seat in the car  Now you can turn the car seat sideways on top of the cart or fit it in the actual cart but that leaves little room for anything else and there is safety issues too  So if you are a single parent or dont have a lot of help with going grocery shopping this could be a concern for you while baby is small and cant sit up by themselvesStroller prosFirst off I LOVE this stroller  I have NEVER had a stroller that is so easy to use and pushes through any terrain with such ease  I keep this stroller in the back of my vehicle at all times and I pull it out and use it so much  I can easily open this stroller with one hand and fold it with one hand  That is literally unheard of in stroller land even with a cheap little umbrella stroller  I have taken this stroller on a nature path full of uneven rocky terrain without a hiccup it rides so smooth  The car seat fits in so easily to the stroller making it basically effortless to get going even when I have 2 older boys and a infant get around by myself  Also I am on the tall side 59 for a girl and I love the adjustable height of the handle  no longer will I kill my back pushing a stroller  I know when my kiddo outgrows the car seat we will still use this stroller for a few years  It has a nice big basket at the bottom multiple drink holders a snack tray and a small item tray for the parent too  I have honestly used this stroller way more than I used the Graco one the entire time I owned it  I think this stroller really makes the travel system  The car seat itself is great but the stroller really takes this system to another level  Did I mention how easy it is to open and fold the stroller and you can do it with one hand  Seriously I cant say enough about this strollerStroller consThe only con I can find right now is that this stroller is massive  I have a Honda Pilot and it takes up a good chunk of my back storage areaand that is saying something  Someone with a smaller vehicle would probably need to see the stroller folded to tell if they are going to have room for it in their vehicleAll in all this is a great system for myself but I dont think it would work for everyone with the weight of the car seat and how big the stroller is  Probably be best to view and get your hands on the system in person before buying

Most negative reviews (limited dictionary):
Prob=0.00 | Review: Looks really cute however the cloth smells funny and gave my baby some rash after 15 mins wearingRequested a return need to pay 25 restocking fee plus shipping25 order maybe 5 back eventuallyAlso the return must be brand new condition Really UnbelievableDo yourself a favor and See the return policy by yourself before making an orderHelloBelow is return instructions this item must not be worn or used or the return will not be refundedThank you for ordering from us Here is your RMA as well as return instructions All returns must be in brand new original condition Please read our return policy Return policy link is provided for you in this emailAll refunds issued are determined by the outcome of inspections Any return of costumes used worn signs of pet hair human hair or washed will void all refund All boxes for shoes NEED to be unmarked and in original condition ALL returns NEED to be in original packaging to qualify for an authorized returnPlease note If you are returning a costume and need a different size we suggest that you place a new order for the item you need This will insure that you get the item quicker If you order from us simply email us your new order and we will waive the restocking fee on your returnsReturn Instructions ALL RETURNS NEED TO BE IN ORIGINAL PACKAGINGItems MUST BE POSTMARKED WITHIN 3 DAYS of  RECEIVING RMA TodaySimply repackage itemon the outside of the packaging please write RMAWe do not cover shipping so please feel free to use any shippingmethod you likeItem is also subject to a 25 restocking fee and all incurred shipping costs associated  with this returnShip to Brands on Sale


Sorted the test reviews by the predicted probability of positive sentiment.

Took:

Top 5 reviews with highest probability → most positive.

Bottom 5 reviews with lowest probability → most negative.

In [59]:
from sklearn.metrics import accuracy_score
accuracy_limited = accuracy_score(y_test, y_pred_limited)
print("Accuracy with limited dictionary:", accuracy_limited)

Accuracy with limited dictionary: 0.8689994303019399

Measure how well the model performs on unseen data.

Accuracy of 86%.

Accuracy: Compare accuracy (all words) vs accuracy_limited (significant words).

Evaluation time: Compare time to train & predict.

Limiting vocabulary usually:

Reduces dimensionality → faster training/prediction.

May slightly reduce accuracy because some informative words are ignored.